name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://v2.velog.io/rss/csj0209"
      - name: Remove square brackets only in blog post list section
        run: |
          awk '
            /<!-- BLOG-POST-LIST START -->/ {flag=1}
            /<!-- BLOG-POST-LIST END -->/ {flag=0}
            { if (flag) { gsub(/\[/, "", $0); gsub(/\]/, "", $0); } print }
            ' README.md > temp.md && mv temp.md README.md

      - name: Commit changes
        run: |
          git config --global user.name 'seung-je'
          git config --global user.email 'csz0209@gmail.com'
          git add README.md
          git commit -m "Remove square brackets from blog post titles" || echo "No changes to commit"
          git push
